apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
        <h1>Hello from app1.</h1>
    </body>
    </html>
