apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-shshimad
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shima8823/IoT-shshimad.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
