apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
        <h1>Hello from app2.</h1>
    </body>
    </html>
