Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  config.vm.define "wilS" do |control|
    control.vm.hostname = "wilS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "wilS"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision :shell, :inline => <<-SHELL
      apt-get update
      apt-get install -y curl wget git vim
    SHELL
    control.vm.provision "shell", path: "scripts/setup_k3s.sh"
    control.vm.provision "shell", path: "scripts/deploy_apps.sh"
  end

end