Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  config.vm.define "shshimadS" do |control|
    control.vm.hostname = "shshimadS"
    control.vm.network "private_network", ip: "192.168.56.110"
	  control.vm.synced_folder "confs/", "/home/vagrant/confs"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "shshimadS"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/setup_k3s.sh"
    control.vm.provision "shell", path: "scripts/deploy_apps.sh"
  end

end