Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-24.04"

  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  # Vagrantコマンドでの仮想マシン指定
  config.vm.define "shshimadS" do |control|
    control.vm.hostname = "shshimadS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      # virtualbox GUI name
      v.customize ["modifyvm", :id, "--name", "shshimadS"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision :shell, :path => "scripts/setup_k3s_server.sh"
  end

  config.vm.define "shshimadSW" do |control|
    control.vm.hostname = "shshimadSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "shshimadSW"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision :shell, :path => "scripts/setup_k3s_agent.sh"
  end

end